core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    path('accounts/', include('allauth.urls')),
    path('social/', include('social.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landing/urls.py
from django.urls import path
from landing.views import Index
from . import views

app_name = 'landing'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path("login/", views.login_request, name="login"),
    path("register/", views.register_request, name="register"),
    path("logout", views.logout_request, name= "logout"),
]

social/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, ProfileView, PostEditView, PostDeleteView, CommentDeleteView, ProfileEditView, AddFollower, RemoveFollower, AddLike, UserSearch, ListFollowers, AddCommentLikes, CommentReplyView, PostNotification, FollowNotification, RemoveNotification, ListThreads, SharedPostView, Explore, ThreadNotification, ThreadView, CreateMessage

app_name = 'social'
 
urlpatterns = [
    path('', PostListView.as_view(), name='post-list'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/edit/<int:pk>/', PostEditView.as_view(), name='post-edit'),
    path('post/delete/<int:pk>/', PostDeleteView.as_view(), name='post-delete'),
    path('post/<int:post_pk>/comment/delete/<int:pk>/', CommentDeleteView.as_view(), name='comment-delete'),
    path('post/<int:post_pk>/comment/<int:pk>/like', AddCommentLikes.as_view(), name='comment-like'),
    
    path('post/<int:pk>/like', AddLike.as_view(), name='like'),

    path('post/<int:post_pk>/comment/reply/<int:pk>', CommentReplyView.as_view(), name='comment-reply'),
    path('post/<int:pk>/share', SharedPostView.as_view(), name='share-post'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('profile/edit/<int:pk>/', ProfileEditView.as_view(), name='profile-edit'),
    path('profile/<int:pk>/followers/add', AddFollower.as_view(), name='add-follower'),
    path('profile/<int:pk>/followers/remove', RemoveFollower.as_view(), name='remove-follower'),
    path('profile/<int:pk>/followers', ListFollowers.as_view(), name='followers-list'),
    path('search/', UserSearch.as_view(), name='profile-search'),
    path('notification/<int:notification_pk>/post/<int:post_pk>', PostNotification.as_view(), name='post-notification'),
    path('notification/<int:notification_pk>/follow/<int:profile_pk>', FollowNotification.as_view(), name='follow-notification'),
    path('notification/<int:notification_pk>/thread/<int:object_pk>', ThreadNotification.as_view(), name='thread-notification'),
    path('notification/delete/<int:notification_pk>', RemoveNotification.as_view(), name='notification-delete'),
    
    path('inbox/', ListThreads.as_view(), name='inbox'),
    
    # path('inbox/create-thread', CreateThread.as_view(), name='create-thread'),
    
    path('inbox/thread/<int:pk>/', ThreadView.as_view(), name='thread'),
    
    path('inbox/<int:pk>/create-message/', CreateMessage.as_view(), name='create-message'),
    
    path('explore/', Explore.as_view(), name='explore'),

    
]

landing/models.py
from django.db import models

# Create your models here.

landing/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)
    
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")
        
        def save(self, commit=True):
            user = super(NewUserForm, self).save(commit=False)
            user.email = self.cleaned_data['email']
            
            if commit:
                user.save()
            return user

landing/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate ,logout
from django.contrib import messages
from .forms import NewUserForm
from django.urls import reverse
from social.models import ThreadModel
from django.db.models import Q

class Index(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'landing/index.html')

@csrf_exempt
def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("social:post-list")
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password")       
    form = AuthenticationForm()
    return render(request=request, template_name="landing/login.html", context={"login_form":form}) 

@csrf_exempt
def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("social:post-list")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render(request, "landing/register.html", {"register_form": form})
        
def logout_request(request):
    logout(request)
    messages.info(request, "You have successfully logged out.")
    return redirect("landing:index")

        

landing/templates/landing/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <script src="https://kit.fontawesome.com/49a2f38d1d.js" crossorigin="anonymous"></script>
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'social/css/stylesheet.css'%}" type="text/css">
  <title>Social Network</title>
</head>

<body id="body">
  {% include 'landing/navbar.html' %}
  {% block content %}
  {% endblock content %}
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
  <script type="text/javascript" src="{% static 'social/js/social.js' %}"></script>
</body>

</html>

landing/templates/landing/index.html
{% extends 'social/base.html' %}

{% block content %}

<div class="container" style="padding-top: 80px;">
    <div class="row justify-content-center mt-5">
        <div class="col-md-10 col-sm-12 text-center">
            <h1 class="display-2">Connect With Your Friends!</h1>
            <p class="mt-3 lead">Follow people who interest you, stay up to date on the latest news and join conversations with your friends!</p>
            <div class="d-flex justify-content-center mt-5">
                <a href="login" class="btn btn-light mr-2">Log In</a>
                <a href="register" class="btn btn-dark">Register</a>
            </div>
        </div>

    </div>

</div>

{% endblock content %}

landing/templates/landing/login.html
{% extends "landing/base.html" %}

{% block content %}

{% load static %}


<div id="login-card" class="card">
  <div class="card-body">
    <h2 class="text-center">Login</h2>
    <br>
    <form method="POST" action="{% url 'landing:login' %}">
      {% csrf_token %}
      <div class="form-group">
        <input type="text" class="form-control" id="email" placeholder="Username" name="username">
      </div>
      <div class="form-group">
        <input type="password" class="form-control" id="email" placeholder="Enter password" name="password">
      </div>
      <button type="submit" id="button" class="btn btn-primary deep-purple btn-block ">Login</button>
      <br>
      <div class="form-group">
        <p class="text-center">Don't have an account? <a href="/register">Create an account</a>.</p>
        <a href="/password_reset">Forgot password?</a>
      </div>

    </form>

  </div>
</div>

{% endblock %}

landing/templates/landing/navbar.html
{% load custom_tags %}
  <!-- Navbar -->
<nav class="navbar navbar-expand fixed-top navbar-light bg-light">
  <div class="container-fluid justify-content-between">
    <!-- Left elements -->
    <div class="d-flex my-2 my-sm-0">
      <!-- Toggler -->
      <!-- Brand -->
      <a class="navbar-brand me-2 mb-1 d-flex align-items-center" {% if user.is_authenticated %} href="{% url 'social:post-list' %}" {% else %}
      href="{% url 'landing:index' %}" {% endif %}>
        <i class="fas fa-comment" style="color: #17a2b8;">Smokey</i>
      </a>
      <!-- Search form -->
      {% if user.is_authenticated %}
      <form class="input-group w-auto my-auto d-none d-sm-flex" method="GET" action="{% url 'social:profile-search' %}">
        <input autocomplete="off" type="search" class="form-control rounded" style="min-width: 125px;"  placeholder="Username" aria-label="Username" aria-describedby="basic-addon1" name="query" value="{{ request.GET.query }}"/>
        <span class="input-group-text border-0 d-none d-lg-flex"><button style="border: none;" type="submit"><i class="fas fa-search"></i></button></i></span>
      </form>
    </div>
    <ul class="navbar-nav flex-row d-none d-md-flex">
      <a href="{% url 'social:explore' %}" style="text-decoration: none; opacity: 0.8; color: #17a2b8;">
        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="35" fill="currentColor" class="bi bi-hash" viewBox="0 0 16 16" >
          <path d="M8.39 12.648a1.32 1.32 0 0 0-.015.18c0 .305.21.508.5.508.266 0 .492-.172.555-.477l.554-2.703h1.204c.421 0 .617-.234.617-.547 0-.312-.188-.53-.617-.53h-.985l.516-2.524h1.265c.43 0 .618-.227.618-.547 0-.313-.188-.524-.618-.524h-1.046l.476-2.304a1.06 1.06 0 0 0 .016-.164.51.51 0 0 0-.516-.516.54.54 0 0 0-.539.43l-.523 2.554H7.617l.477-2.304c.008-.04.015-.118.015-.164a.512.512 0 0 0-.523-.516.539.539 0 0 0-.531.43L6.53 5.484H5.414c-.43 0-.617.22-.617.532 0 .312.187.539.617.539h.906l-.515 2.523H4.609c-.421 0-.609.219-.609.531 0 .313.188.547.61.547h.976l-.516 2.492c-.008.04-.015.125-.015.18 0 .305.21.508.5.508.265 0 .492-.172.554-.477l.555-2.703h2.242l-.515 2.492zm-1-6.109h2.266l-.515 2.563H6.859l.532-2.563z"/>
        </svg>
      </a>
    </ul>
    <ul class="navbar-nav flex-row">
      <li class="nav-item me-3 me-lg-1">
        <a class="nav-link d-sm-flex align-items-sm-center" href="{% url 'social:profile' user.profile.pk %}">
          <img src="{{request.user.profile.picture.url}}" class="rounded-circle" height="22" alt=""
            loading="lazy"/>
          <strong class="d-none d-sm-block ms-1">{{request.user.username}}</strong>
        </a>
      </li>
      <li class="nav-item dropdown me-3 me-lg-1">
        <a class="nav-link" href="{% url 'social:inbox'%}" id="navbarDropdownMenuLink" role="button" aria-expanded="false">
          <i class="fas fa-comments fa-lg"></i>
        </a>
      </li>
      <div class="icon me-3 me-lg-1" id="bell">
          <i class="fas fa-bell fa-lg">{% show_notifications %}</i>
      </div>
      <li class="nav-item dropdown me-3 me-lg-1">
          <li class="bi bi-box-arrow-left"><a class="dropdown-item" href="/logout">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-left" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M6 12.5a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v2a.5.5 0 0 1-1 0v-2A1.5 1.5 0 0 1 6.5 2h8A1.5 1.5 0 0 1 16 3.5v9a1.5 1.5 0 0 1-1.5 1.5h-8A1.5 1.5 0 0 1 5 12.5v-2a.5.5 0 0 1 1 0v2z"></path>
              <path fill-rule="evenodd" d="M.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L1.707 7.5H10.5a.5.5 0 0 1 0 1H1.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3z"></path>
            </svg>
            Logout
        </a>
        </li>
      </li>
    </ul>

    {% endif %}
    <!-- Right elements -->
  </div>
</nav>
<!-- Navbar -->

landing/templates/landing/register.html
{% extends "landing/base.html" %}

{% block content %} 

{% load crispy_forms_tags %}         

<!--Register--> 
<div class="container py-5">
	<h1>Register</h1>
	<form method="POST">
		{% csrf_token %}
		{{ register_form|crispy }}                    
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="/login">login</a> instead.</p>
</div>

{% endblock %}