core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    path('accounts/', include('allauth.urls')),
    path('social/', include('social.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, ProfileView, PostEditView, PostDeleteView, CommentDeleteView, ProfileEditView, AddFollower, RemoveFollower, AddLike, UserSearch, ListFollowers, AddCommentLikes, CommentReplyView, PostNotification, FollowNotification, RemoveNotification, ListThreads, SharedPostView, Explore, ThreadNotification, ThreadView, CreateMessage

app_name = 'social'
 
urlpatterns = [
    path('', PostListView.as_view(), name='post-list'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/edit/<int:pk>/', PostEditView.as_view(), name='post-edit'),
    path('post/delete/<int:pk>/', PostDeleteView.as_view(), name='post-delete'),
    path('post/<int:post_pk>/comment/delete/<int:pk>/', CommentDeleteView.as_view(), name='comment-delete'),
    path('post/<int:post_pk>/comment/<int:pk>/like', AddCommentLikes.as_view(), name='comment-like'),
    
    path('post/<int:pk>/like', AddLike.as_view(), name='like'),

    path('post/<int:post_pk>/comment/reply/<int:pk>', CommentReplyView.as_view(), name='comment-reply'),
    path('post/<int:pk>/share', SharedPostView.as_view(), name='share-post'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('profile/edit/<int:pk>/', ProfileEditView.as_view(), name='profile-edit'),
    path('profile/<int:pk>/followers/add', AddFollower.as_view(), name='add-follower'),
    path('profile/<int:pk>/followers/remove', RemoveFollower.as_view(), name='remove-follower'),
    path('profile/<int:pk>/followers', ListFollowers.as_view(), name='followers-list'),
    path('search/', UserSearch.as_view(), name='profile-search'),
    path('notification/<int:notification_pk>/post/<int:post_pk>', PostNotification.as_view(), name='post-notification'),
    path('notification/<int:notification_pk>/follow/<int:profile_pk>', FollowNotification.as_view(), name='follow-notification'),
    path('notification/<int:notification_pk>/thread/<int:object_pk>', ThreadNotification.as_view(), name='thread-notification'),
    path('notification/delete/<int:notification_pk>', RemoveNotification.as_view(), name='notification-delete'),
    
    path('inbox/', ListThreads.as_view(), name='inbox'),
    
    # path('inbox/create-thread', CreateThread.as_view(), name='create-thread'),
    
    path('inbox/thread/<int:pk>/', ThreadView.as_view(), name='thread'),
    
    path('inbox/<int:pk>/create-message/', CreateMessage.as_view(), name='create-message'),
    
    path('explore/', Explore.as_view(), name='explore'),

    
]

social/forms.py
from django import forms
from .models import Post, Comment, MessageModel

class PostForm(forms.ModelForm):
    body = forms.CharField(
        label='',
        widget=forms.Textarea(
            attrs={
                'rows': '3',
                'cols': '50',
                'style': 'height: 5em;'
                
            }))
    
    image = forms.ImageField(
        required=False,
        widget=forms.ClearableFileInput(attrs={
            'multiple': True    
        }))
    
    class Meta:
        model = Post
        fields = ['body']
        
class CommentForm(forms.ModelForm):
    comment = forms.CharField(
        label='',
        widget=forms.Textarea(
            attrs={
                'rows': '3',
                'placeholder': 'Say Something...'
            }
        )
    )
    class Meta:
        model = Comment
        fields = ['comment']
   
# Input for the person we want to talk to     
class ThreadForm(forms.Form):
    username = forms.CharField(label='', max_length=100)


class MessageForm(forms.ModelForm):
    #message = forms.CharField(label='', max_length=1000)
    body = forms.CharField(label='', max_length=1000)
    image = forms.ImageField(label='Send an Image', required=False)
    
    class Meta:
        model = MessageModel
        fields = ['body', 'image']
        
class SharedForm(forms.Form):
    body = forms.CharField(
        label='',
        widget=forms.Textarea(attrs={
            'rows': '3',
            'placeholder': 'Say Something...'
        }))
    
class ExploreForm(forms.Form):
    query = forms.CharField(
        label='',
        widget=forms.TextInput(attrs={
            'placeholder': 'Explore tags'
        })
    )

social/views.py
from django.shortcuts import render, redirect
from django.views import View
from .models import Post, Comment, UserProfile,Notification, ThreadModel, MessageModel, Image, Tag
from .forms import PostForm, CommentForm, ThreadForm, MessageForm, SharedForm, ExploreForm
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User
from django.views.generic.edit import UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.http import HttpResponseRedirect, HttpResponse
from django.db.models import Q, Count
from django.contrib import messages
from django.utils import timezone
from django.shortcuts import get_object_or_404

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

class PostListView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        profile = UserProfile.objects.get(user = request.user)
        form = PostForm()
        share_form = SharedForm()
        profile_list = profile.followers.all()[:5]
        post_list = Post.objects.get_following_posts(
            user = request.user
        )
                
        most_popular_posts = Post.objects.annotate(
            num_comments=Count('comments')).order_by('-num_comments')[:3]
        
        posts = Paginator(post_list, 10)
        
        page_numb = request.GET.get('page')
        
        try:
            page_obj = posts.get_page(page_numb)
        except PageNotAnInteger:
            page_obj = posts.page(1)
        except EmptyPage:
            page_obj = posts.page(posts.num_pages)
        
        form = PostForm()

        context = {
            'page_obj': page_obj,
            'post_list': post_list,
            'shareform': share_form,
            'form': form,
            'profile_list': profile_list,
            'most_popular_posts': most_popular_posts
        }
        return render(request, 'social/post_list.html', context)
    
    def post(self, request, *args, **kwargs):
        share_form = SharedForm()
        
        post_list = Post.objects.get_following_posts(
            user = request.user
        )
        
        profile_list = UserProfile.objects.all()[:10]
        
        form = PostForm(request.POST, request.FILES)
        
        files = request.FILES.getlist('image')
        

        most_popular_posts = Post.objects.annotate(num_comments=Count('comments')).order_by('-num_comments')[:10]
        
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.assign_author(author=request.user)
            new_post.create_tags()
            
            for file in files:
                img = Image.objects.create(
                    image = file,
                )
                new_post.image.add(img)
                

        form = PostForm(request.POST, request.FILES)        
        context = {
            'post_list': post_list,
            'shareform': share_form,
            'form': form,
            'profile_list': profile_list,
            'most_popular_posts':most_popular_posts,
        }
        
        return render(request, 'social/post_list.html', context)
    
class PostDetailView(LoginRequiredMixin, View):
    def get(self, request, pk, *args, **kwargs):
        form = CommentForm()
        
        post = get_object_or_404(Post, pk=pk)
        
        comments = Comment.objects.related_post(post=post)
        
        context = {
            'post': post,
            'form': form,
            'comments': comments,
        }
        return render(request, 'social/post_detail.html', context)
    
    def post(self, request, pk, *args, **kwargs):
        form = CommentForm(request.POST)
        post = get_object_or_404(Post, pk=pk)
        comments = Comment.objects.related_post(post=post)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.save_data(
                author=request.user,
                post=post
            )
            new_comment.create_tags()
       
        Notification.objects.add_comment(
            form_user=request.user,
            to_user=post.author,
            post=post
        )
        
        form = CommentForm()

        context = {
            'post': post,
            'form': form,
            'comments': comments,
        }
        return render(request, 'social/post_detail.html', context)
    
class CommentReplyView(LoginRequiredMixin, View):
    def post(self, request, post_pk, pk, *args, **kwargs):
        form = CommentForm(request.POST)
        
        post = get_object_or_404(Post, pk=post_pk)
        
        parent_comment = get_object_or_404(Comment, pk=pk)

        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.save_data(
                author=request.user,
                post=post,
                parent=parent_comment
            )

        Notification.objects.add_comment(
            form_user=request.user,
            to_user=parent_comment.author,
            comment=new_comment
        )
        return redirect('social:post-detail', pk=post_pk)
 
class PostEditView(LoginRequiredMixin, UserPassesTestMixin ,UpdateView):
    model = Post
    fields = ['body']
    template_name = 'social/post_edit.html'
    
    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('social:post-detail', kwargs={'pk': pk})
    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = 'social/post_delete.html'
    success_url = reverse_lazy('social:post-list')
    
    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author
    
class SharedPostView(View):
    def post(self, request, pk, *args, **kwargs):
        form = SharedForm(request.POST)
        
        original_post = Post.objects.get(pk=pk)
        
        if form.is_valid():
            new_post = Post.objects.create(
                shared_body = self.request.POST.get('body'),
                body = original_post.body,
                author = original_post.author,
                created_on = original_post.created_on,
                shared_user = request.user,
                shared_on = timezone.now(),
            )
            
            new_post.image.add(*original_post.image.all())
        return redirect('social:post-list')
    

class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Comment
    template_name = 'social/comment_delete.html'
    
    def get_success_url(self):
        pk = self.kwargs['post_pk']
        return reverse_lazy('social:post-detail', kwargs={'pk': pk})
    def test_func(self):
        comment = self.get_object()
        return self.request.user == comment.author
    
class AddCommentLikes(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        comment = get_object_or_404(Comment, pk=pk)
        
        if comment.likes.filter(pk=request.user.pk).exists():
            comment.likes.remove(request.user)
        else:
            comment.likes.add(request.user)
            Notification.objects.add_like(
                form_user=request.user,
                to_user=comment.author,
                comment=comment
            )

        next = request.POST.get('next', '/  ')
        return HttpResponseRedirect(next)

    
class ProfileView(View):
    def get(self, request, pk, *args, **kwargs):
        profile = UserProfile.objects.get(pk=pk)
        user = profile.user
        posts = Post.objects.filter(author=user).order_by('-created_on')
        images = Post.objects.filter(author=user).order_by('-created_on')[:3]

        followers = profile.followers.all()
        is_following = True if followers else False 
        for follower in followers:
            if follower == request.user:
                is_following = True
                break
            else:
                is_following = False
                
        number_of_followers = len(followers)
        followers = profile.followers.all()
        context = {
            'user': user,
            'profile': profile, 
            'posts': posts,
            'is_following': is_following,
            'number_of_followers': number_of_followers,
            'followers': followers,
            'images': images,
        }
        return render(request, 'social/profile.html', context)
        
class ProfileEditView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = UserProfile
    fields = ['name', 'bio', 'birth_date', 'location', 'picture']
    template_name = 'social/profile_edit.html'
    
    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('social:profile', kwargs={'pk': pk})
    def test_func(self):
        return self.request.user == self.get_object().user

class AddFollower(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        profile = get_object_or_404(UserProfile, pk=pk)
        
        profile.followers.add(request.user)
        
        Notification.objects.add_follow(
            form_user=request.user,
            to_user=profile.user
        )
        
        return redirect('social:profile', pk=pk)

class RemoveFollower(LoginRequiredMixin, View):
    def post(self,request, pk, *args, **kwargs):
        profile = get_object_or_404(UserProfile, pk=pk)
        
        profile.followers.remove(request.user)
        
        return redirect('social:profile', pk=profile.pk)
    
class ListFollowers(View):
    def get(self, request, pk, *args, **kwargs):
        profile = UserProfile.objects.get(pk=pk)
        followers = profile.followers.all()
        
        context = {
            'profile': profile,

social/templates/social/comment_delete.html
{% extends 'landing/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-md-3 col-sm-6">
            <a href="{% url 'social:post-detail' object.post.pk %}" class="btn btn-light">Back to Feed</a>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5 col-sm-12">
            <h5>Are You Sure?</h5>
            <p>You are about to delete this comment, this cannot be undone.</p>
        <form method="POST">
            {% csrf_token %}
            <div class="d-grid gap-2">
                <button type="submit" class="btn btn-danger">Delete</button>
            </div>
        </form>
    </div>
    </div>
</div>
{% endblock content %}

social/templates/social/create_thread.html
{% extends 'landing/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
        <div class="row">
            <div class="col-md-12 p-5">
                <a href="{% url 'social:inbox' %}" class="btn btn-light">Back to your inbox</a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 p-5">
                <h3>Start a Conversation!</h3>
            </div>
        </div>
        <div class="row justify-content-center mt-3 mb-5">
            <div class="col-md-5 col-sm-12">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-danger" role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
                <form method="POST">
                    {% csrf_token%}
                    <p>Enter the username for the person your would like to talk to.</p>
                    {{ form | crispy}}
                    <div class="d-grid gab-2">
                        <button class="btn btn-success mt-3" type="submit">Continue</button>
                    </div>
                </form>
            </div>  
        </div>
</div>
{% endblock content %}

social/templates/social/explore.html
{% extends 'social/base.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <div class="container">
        <div class="row mt-5">
            <div class="col-md-5 col-sm-6">
                <a href="{% url 'social:post-list' %}" class="btn btn-light">Back To Feed</a>
            </div>
        </div>
        <div class="row justify-content-center mt-3">
            <div class="col-md-5 col-sm-12">
                {% if tag %}
                    <h3>Explore #{{ tag.name }} Posts</h3>
                    <p class="mb-3">Most recent posts tagged with {{ tag.name }}</p>
                {% else %}
                    <h3>Explore Posts</h3>
                    <p class="mb-3">Explore tags to find new posts</p>
                {% endif %}
                <form method="POST" class="mb-5">
                    {% csrf_token %}
                    {{ explore_form | crispy }}
                </form>
            </div>
        </div>

        {% for post in posts %}
        <div class="row justify-content-center mt-3">
            <div class="col-md-5 col-sm-12 border-bottom position-relative">
                {% if post.shared_user %}
                <div>
                    <a href="{% url 'social:profile' post.shared_user.profile.pk %}">
                        <img class="round-circle post-img" height="30" width="30" src="{{ post.shared_user.profile.picture.url }}">
                    </a>
                    <p class="post-text">
                        <a class="text-primary post-link" href="{% url 'social:profile' post.shared_user.profile.pk %}">@{{ post.shared_user }}</a> shared a post on {{ post.shared_on }}
                    </p>
                </div>
                {% else %}
                <div>
                    <a href="{% url 'social:profile' post.author.profile.pk %}">
                        <img class="round-circle post-img" height="30" width="30" src="{{ post.author.profile.picture.url }}" >
                    </a>
                    <p class="post-text">
                        <a class="text-primary post-link" href="{% url 'social:profile' post.author.profile.pk %}">@{{ post.author }}</a> {{ post.created_on }}
                        <span onclick="shareToggle('{{ post.pk }}')"><i class="far fa-share-square share-btn"></i></span>
                    </p>
                </div>
                {% endif %}
                <form method="POST" action="{% url 'social:share-post' post.pk %}" class="d-none" id="{{ post.pk }}">
                    {% csrf_token %}
                    {{ shareform | crispy}}
                    <div class="d-grid gap-2">
                        <button class="btn btn-success mt-3">Share the post</button>
                    </div>
                </form>
                {% if post.shared_body %}
                <div class="position-relative border-bottom mb-3 body">
                    <p>{{ post.shared_body }}</p>
                </div>
                <div class="shared-post">
                    <a href="{% url 'social:profile' post.author.profile.pk %}">
                        <img class="round-circle post-img" height="30" width="30" src="{{ post.author.profile.picture.url }}">
                    </a>
                    <p class="post-text">
                        <a class="text-primary post-link" href="{% url 'social:profile' post.author.profile.pk %}">@{{ post.author }}</a> {{ post.created_on }}
                    </p>
                </div>
                {% endif %}
                <div class="shared-post position-relative pt-3">
                    {% if post.image.count > 0 %}
                        <div class="row">
                            {% for img in post.image.all %}
                                <div class="col-md-4 col-xs-12">
                                    <img src="{{ img.image.url }}" class="post-image">
                                </div>
                            {% endfor %}
                        </div>
                    {% endif %}
                    <div class="body">
                        <p>{{ post.body }}</p>
                    </div>
                    <a href="{% url 'social:post-detail' post.pk %}" class="stretched-link"></a>
                </div>
                
                <div class="d-flex flex-row">
                    <form method="POSt" action="{% url 'social:like' post.pk %}">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ request.path }}">
                        <button class="remove-default-btn" type="submit">
                            <i class="far fa-thumbs-up"> <span>{{ post.likes.all.count }}</span></i>
                        </button>
                    </form>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock content %}

social/templates/social/show_notifications.html
<style>
    @import url('https://fonts.googleapis.com/css2?family=Manrope:wght@200&display=swap');

    * {
        padding: 0px;
        margin: 0px
    }

    .icon {
        padding-top: 9px;
        color: #000;
        
        
    }

    .icon img {
        display: inline-block;
        width: 26px;
        margin-top: 4px;
        
    }

    .notifications::-webkit-scrollbar-track
    {
        -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
        background-color: #F5F5F5;
        border-radius: 5px
    }
    
    .notifications::-webkit-scrollbar
    {
        width: 10px;
        background-color: #F5F5F5;
        border-radius: 5px
    }
    
    .notifications::-webkit-scrollbar-thumb
    {
        background-color: black;
        border: 2px solid black;
        border-radius: 5px
    }
    .notifications {
        width: 300px;
        height: 0px;
        border-radius: 10px;
        transition: 0.5s;
        position: absolute;
        overflow-y: scroll;
        top: 63px;
        right: 62px;
        padding: 0px;
        margin-top: 5px;
        background-color: #F4F4F4;
        -webkit-box-shadow: 10px 10px 23px 0px rgba(0,0,0,0.2);
        -moz-box-shadow: 10px 10px 23px 0px rgba(0,0,0,0.1);
        box-shadow: 10px 10px 23px 0px rgba(0,0,0,0.1);
        cursor: context-menu;
    }

    .notifications h2 {
        font-size: 14px;
        padding: 10px;
        border-bottom: 1px solid #eee;
        color: #999
    }

    .notifications h2 span {
        color: #f00
    }

    .notifications-item {
        display: flex;
        border-bottom: 1px solid #eee;
        padding: 6px 9px;
        margin-bottom: 0px;

    }



    .notifications-item img {
        display: block;
        width: 50px;
        height: 50px;
        margin-right: 9px;
        border-radius: 50%;
        margin-top: 2px
    }

    .notifications-item .text h4 {
        color: #777;
        font-size: 16px;
        margin-top: 3px
    }

    .notifications-item .text p {
        color: #aaa;
        font-size: 12px
    }
</style>

<!-- <div class="dropdown">
    <span class="badge bg-primary notification-badge" onclick="showNotifications()">{{ notifications.count }}</span>
    <div class="dropdown-content d-none" id="notification-container">
        {% for notification in notifications %}
            {% if notification.post %}
                {% if notification.NOTIFICATION_TYPE_LIKE %}
                <div class="dropdown-item-parent">  
                    <a href="{% url 'social:post-notification' notification.pk notification.post.pk %}">@{{ notification.form_user }} liked your post</a>
                    <span class="dropdown-item-close" onclick="removeNotification(`{% url 'social:notification-delete' notification.pk %}`, `{{ request.path }}`)">&times;</span>
                </div>
                {% elif notification.NOTIFICATION_TYPE_COMMENT %}
                <div class="dropdown-item-parent">
                    <a href="{% url 'social:post-notification' notification.pk notification.post.pk %}">@{{ notification.form_user }} comment on your post</a>
                    <span class="dropdown-item-close" onclick="removeNotification(`{% url 'social:notification-delete' notification.pk %}`, `{{ request.path }}`)">&times;</span>
                </div>
                {% endif %}
            {% elif notification.comment %}
                {% if notification.NOTIFICATION_TYPE_LIKE %}
                <div class="dropdown-item-parent">
                    <a href="{% url 'social:post-notification' notification.pk notification.comment.post.pk %}">@{{ notification.form_user }} replied to your comment</a>
                    <span class="dropdown-item-close" onclick="removeNotification(`{% url 'social:notification-delete' notification.pk %}`, `{{ request.path }}`)">&times;</span>
                </div>    
                {% endif %}
            {% elif notification.thread %}
                <div class="dropdown-item-parent">
                    <a href="{% url 'social:thread-notification' notification.pk notification.thread.pk %}">@{{ notification.form_user }} sent you a message</a>
                    <span class="dropdown-item-close" onclick="removeNotification(`{% url 'social:notification-delete' notification.pk %}`, `{{ request.path }}`)">&times;</span>
                </div>
            {% else %}
            <div class="dropdown-item-parent">
                <a href="{% url 'social:follow-notification' notification.pk notification.form_user.profile.pk %}">@{{notification.form_user}} has started following you</a>
                <span class="dropdown-item-close" onclick="removeNotification(`{% url 'social:notification-delete' notification.pk %}`, `{{ request.path }}`)">&times;</span>
            </div>
        {% endif %}
        {% endfor %}
    </div>
</div> -->
<span class="badge rounded-pill badge-notification bg-danger" onclick="showNotifications()">{{ notifications.count }}</span>
<div>
    <div class="notifications" id="box">
        <h2>Notifications - <span  onclick="showNotifications()">{{ notifications.count }}</span></h2>
        {% for notification in notifications %}
        {% if notification.post %}
        {% if notification.NOTIFICATION_TYPE_LIKE %}
        <div class="notifications-item"> 
            <div class="pull-left image">
                <a href="{% url 'social:post-notification' notification.pk notification.post.pk %}"><img src="{{ notification.form_user.profile.picture.url }}"></a>
            </div>
            <div class="text">
                <div>
                    <h4>{{ notification.form_user }}</h4>
                    <p>{{ notification.form_user }} liked your post</p>
                </div>
            </div>
            <div>
                <span onclick="removeNotification(`{% url 'social:notification-delete' notification.pk %}`, `{{ request.path }}`)">&times;</span>
            </div>
        </div>
        {% elif notification.NOTIFICATION_TYPE_COMMENT %}
        <div class="notifications-item"> 
            <div class="pull-left image">
                <a href="{% url 'social:post-notification' notification.pk notification.post.pk %}"><img src="{{ notification.form_user.profile.picture.url }}" alt="img"></a>
            </div>
            <div class="text">
                <div>
                    <h4>{{ notification.form_user }}</h4>
                    <p>{{ notification.form_user }} Comment in your post</p>
                </div>
            </div>
            <div>
                <span class="dropdown-item-close" onclick="removeNotification(`{% url 'social:notification-delete' notification.pk %}`, `{{ request.path }}`)">&times;</span>
            </div>
        </div>
        {% endif %}
    {% elif notification.comment %}
        {% if notification.NOTIFICATION_TYPE_LIKE %}
        <div class="notifications-item"> 
            <div class="pull-left image">
                <a href="{% url 'social:post-notification' notification.pk notification.comment.post.pk %}"><img src="{{ notification.form_user.profile.picture.url }}" alt="img"></a>
            </div>
            <div class="text">
                <div>
                    <h4>{{ notification.form_user }}</h4>
                    <p>{{ notification.form_user }} Replied to Your Comment</p>
                </div>
            </div>
            <div>
                <span class="dropdown-item-close" onclick="removeNotification(`{% url 'social:notification-delete' notification.pk %}`, `{{ request.path }}`)">&times;</span>
            </div>
        </div>
        {% endif %}
            {% elif notification.thread %}
            <div class="notifications-item"> 
                <div class="pull-left image">
                    <a href="{% url 'social:thread-notification' notification.pk notification.thread.pk %}"><img src="{{ notification.form_user.profile.picture.url }}" alt="img"></a>
                </div>
                <div class="text">
                    <div>
                        <h4>{{ notification.form_user }}</h4>
                        <p>{{ notification.form_user }} Sent you a message</p>
                    </div>
                </div>
                <div>
                    <span class="dropdown-item-close" onclick="removeNotification(`{% url 'social:notification-delete' notification.pk %}`, `{{ request.path }}`)">&times;</span>
                </div>
            </div>
        {% else %}
        <div class="notifications-item"> 
            <div class="pull-left image">
                <a href="{% url 'social:follow-notification' notification.pk notification.form_user.profile.pk %}"><img src="{{ notification.form_user.profile.picture.url }}" alt="img"></a>
            </div>
            <div class="text">
                <div>
                    <h4>{{ notification.form_user }}</h4>
                    <p>{{ notification.form_user }} has started following you</p>
                </div>
            </div>
            <div>
                <span class="dropdown-item-close" onclick="removeNotification(`{% url 'social:notification-delete' notification.pk %}`, `{{ request.path }}`)">&times;</span>
            </div>
        </div>
{% endif %}
{% endfor %}
    </div>
</div>

<script>
    $(document).ready(function(){
        var down = false;
        
        $('#bell').click(function(e){
          
            var color = $(this).text();
            if(down){
                
                $('#box').css('height','0px');
                $('#box').css('opacity','0');
                down = false;
            }else{
                
                $('#box').css('height','auto');
                $('#box').css('opacity','1');
                down = true;
                
            }
            
        });
            
    });
</script>